fixed check

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -38,30 +38,30 @@ jobs:
       run: terraform plan -out=tfplan -var-file=Vars/kube_deploy.tfvars | tee plan_output.txt
       working-directory: Infra
 
-    # Extract Plan
-    - name: Check Terraform Plan for Additions or Destroys
-      id: check_plan
-      run: |
-        sed 's/\x1b\[[0-9;]*m//g' Infra/plan_output.txt > Infra/plan_clean_output.txt
-        ADDS=$(grep "Plan: " Infra/plan_clean_output.txt | awk '{print $2}')
-        CHANGES=$(grep "Plan: " Infra/plan_clean_output.txt | awk '{print $4}')
-        DESTROYS=$(grep "Plan: " Infra/plan_clean_output.txt | awk '{print $6}')
-
-        echo "Adds: $ADDS, Changes: $CHANGES, Destroys: $DESTROYS"
-
-        if [[ "$ADDS" -gt 0 || "$DESTROYS" -gt 0 ]]; then
-          echo "manual_approval=true" >> $GITHUB_ENV
-        else
-          echo "manual_approval=false" >> $GITHUB_ENV
-        fi
-    
-    # If manual approval is required, wait for manual intervention
-    - name: Manual Approval
-      if: env.manual_approval == 'true'
-      run: |
-        echo "Manual approval required before applying changes."
-        exit 1  # This is just to pause the workflow until you manually approve
+    ## Extract Plan
+    #- name: Check Terraform Plan for Additions or Destroys
+    #  id: check_plan
+    #  run: |
+    #    sed 's/\x1b\[[0-9;]*m//g' Infra/plan_output.txt > Infra/plan_clean_output.txt
+    #    ADDS=$(grep "Plan: " Infra/plan_clean_output.txt | awk '{print $2}')
+    #    CHANGES=$(grep "Plan: " Infra/plan_clean_output.txt | awk '{print $4}')
+    #    DESTROYS=$(grep "Plan: " Infra/plan_clean_output.txt | awk '{print $6}')
+#
+    #    echo "Adds: $ADDS, Changes: $CHANGES, Destroys: $DESTROYS"
+#
+    #    if [[ "$ADDS" -gt 0 || "$DESTROYS" -gt 0 ]]; then
+    #      echo "manual_approval=true" >> $GITHUB_ENV
+    #    else
+    #      echo "manual_approval=false" >> $GITHUB_ENV
+    #    fi
+    #
+    ## If manual approval is required, wait for manual intervention
+    #- name: Manual Approval
+    #  if: env.manual_approval == 'true'
+    #  run: |
+    #    echo "Manual approval required before applying changes."
+    #    exit 1  # This is just to pause the workflow until you manually approve
 
     - name: Apply Terraform
-      run: terraform apply -var-file=Vars/kube_deploy.tfvars
+      run: terraform apply -auto-approve -var-file=Vars/kube_deploy.tfvars
       working-directory: Infra
